### PR TITLE
Wrong env var for `maxRows`

### PR DESCRIPTION
**Pull request by mindflayer**
See https://postgrest.org/en/stable/references/configuration.html#environment-variables

### CODE REVIEW

**Comment by mindflayer** [comment]
@colearendt Could you please have a look at this simple one?

**Comment by colearendt** [comment]
Woops! Totally missed this! This looks great, thanks!

**Comment by mindflayer** [comment]
Hi @colearendt, are you planning to merge this change?
Thanks in advance!

**Comment by colearendt** [comment]
Merp. Slacker status over here. Can you tell I've been struggling to keep track of my notifications? 🙈 Sorry for the delay!

**Pull request merged**
